all:
     go build ./lab_01/hello.go
      #- export GOOS="darwin"
      #- go build -o lab_01/out/$GOOS/hello ./lab_01/hello.go 
      #- export GOOS="linux"
      #- go build -o lab_01/out/$GOOS/hello ./lab_01/hello.go 
      #- export GOOS="windows"
      #- go build -o lab_01/out/$GOOS/hello.exe ./lab_01/hello.go 
